version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik

  - package-ecosystem: npm
    directory: "/lib/"
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "01:30"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik

  - package-ecosystem: npm
    directory: "/cli/"
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik

  - package-ecosystem: npm
    directory: "/deploy-test/"
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
