version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "00:30"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    labels:
      - automerge

  - package-ecosystem: npm
    directory: "/"
    versioning-strategy: increase-if-necessary
    schedule:
      interval: daily
      time: "01:30"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    labels:
      - automerge

  - package-ecosystem: npm
    directory: "/tests-cli/"
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "02:30"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    labels:
      - automerge
