extends: default

rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 1
  document-end:
    present: false
  document-start:
    present: false
  line-length:
    max: 180
  truthy:
    allowed-values: ['true', 'false', 'on']
