pull_request_rules:
  - name: Automatic Merge (for Owner)
    conditions:
      - author=matejkosiarcik
      - assignee=matejkosiarcik
      - base=master
      - label!=work-in-progress
      - -title~=^.*((wip)|(WIP)|(Wip)).*$
      - -conflict
      - -merged
      - -locked
      - -draft
      - head~=^(develop|feature-.+)$
    actions:
      merge:
        method: merge
        strict: smart
        strict_method: rebase

  - name: Automatic merge for dependabot
    conditions:
      - author=dependabot[bot]
      - base=master
      - assignee=matejkosiarcik
    actions:
      merge:
        method: rebase
        strict: true

  - name: Automatic merge for defaults update
    conditions:
      - author=github-actions[bot]
      - title=Update defaults
      - base=master
      - assignee=matejkosiarcik
    actions:
      merge:
        method: rebase
        strict: true
