version: 2.1

workflows:
  version: 2
  circleci-build:
    jobs:
      - azlint
      - lint
      - build

jobs:
  azlint:
    docker:
      - image: matejkosiarcik/azlint
    steps:
      - checkout
      - run: |
          if [ "$CIRCLE_BRANCH" = main ]; then
            azlint
          else
            azlint --only-changed
          fi

  lint:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run: |
          curl -fLsS https://deb.nodesource.com/setup_lts.x | bash -
          DEBIAN_FRONTEND=noninteractive apt-get install --yes --no-install-recommends nodejs
      - run: make bootstrap lint

  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run: |
          curl -fLsS https://deb.nodesource.com/setup_lts.x | bash -
          DEBIAN_FRONTEND=noninteractive apt-get install --yes --no-install-recommends nodejs jq
      - run: make
