version: 2.1

workflows:
  version: 2
  circleci-build:
    jobs:
      - azlint
      - build: { matrix: { parameters: { node_version: [ latest, lts ] }}}

jobs:
  azlint:
    docker:
      - image: matejkosiarcik/azlint
    steps:
      - checkout
      - setup_remote_docker
      - run: azlint

  build:
    parameters:
      node_version:
        type: string
    docker:
      - image: "node:<< parameters.node_version >>"
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: make bootstrap
      - run: make lint
      - run: make build
      - run: make test
