version: 2.1

workflows:
  version: 2
  circleci-build:
    jobs:
      - azlint
      - lint
      - build:
          matrix:
            parameters:
              node_version:
                - latest
                - lts
                - current-alpine
                - lts-alpine

jobs:
  azlint:
    docker:
      - image: matejkosiarcik/azlint
    steps:
      - checkout
      - setup_remote_docker
      - run: azlint

  lint:
    docker:
      - image: node:lts
    steps:
      - checkout
      - run: npm ci && npm run lint

  build:
    parameters:
      node_version:
        type: string
    docker:
      - image: "node:<< parameters.node_version >>"
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: (apt-get update && apt-get install -y jq) || apk add jq make bash
      - run: make bootstrap build test
