name: AutoMerge

on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Automerge 🎋 for dependabot 🤖
        uses: pascalgn/automerge-action@v0.13.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: automerge
          MERGE_METHOD: rebase
          MERGE_FILTER_AUTHOR: dependabot[bot]
          MERGE_RETRIES: 0
          MERGE_FORKS: false
          UPDATE_LABELS: autoupdate,never  # should not actually update
          UPDATE_METHOD: rebase
          UPDATE_RETRIES: 0
